[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://darmoc-client.netlify.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"
